spryk: template
description: "Adds a new *module*Config to the Yves application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Yves/YvesConfig.php.twig

  targetFilename:
    value: "{{ module }}Config.php"

  targetPath:
    value: "src/{{ organization }}/Yves/{{ module }}/"

preSpryks:
  - AddModule
