spryk: template
description: "Adds a new *module*Factory to the Yves application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Yves/YvesFactory.php.twig

  targetFilename:
    value: "{{ module }}Factory.php"

  targetPath:
    value: "src/{{ organization }}/Yves/{{ module }}/"

preSpryks:
  - AddModule

postSpryks:
  - AddZedBusinessFacade
  - AddYvesDependencyProvider
  - AddZedConfig
