spryk: template
description: "Adds a new *module*DependencyProvider to the Yves application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Yves/YvesDependencyProvider.php.twig

  targetFilename:
    value: "{{ module }}DependencyProvider.php"

  targetPath:
    value: "src/{{ organization }}/Yves/{{ module }}/"

preSpryks:
  - AddModule
