spryk: template
description: "Adds a new *module*To*dependentModule*FacadeBridge."
mode: "core|sdk|eco"

arguments:
  module:
    moduleFilter:
      application: Zed

  organization:
    inherit: true
    default: Spryker

  dependentModule:
    inherit: true
    moduleFilter:
      application: Zed

  dependentModuleOrganization:
    default: Spryker


  template:
    value: Zed/Dependency/Facade/ZedDependencyFacadeBridge.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}FacadeBridge.php"

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Dependency/Facade/"

preSpryks:
  - AddModule

postSpryks:
  - AddZedDependencyFacadeInterface
  - AddZedDependencyFacadeBusinessFactoryMethod
  - AddZedDependencyFacadeDependencyProviderMethod
  - AddZedDependencyFacadeDependencyProviderConstant:
      arguments:
          name:
            value: "FACADE_{{ dependentModule | underscored | upper }}"
          value:
            value:  "{{ dependentModule | camelCaseToWhitespace | lower }} facade"
          visibility:
            value:  "public"
