spryk: template
description: "Adds a new *module*FacadeTest."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Business/ZedBusinessFacadeTest.php.twig

  targetFilename:
    value: "{{ module }}FacadeTest.php"

  targetPath:
    value: "tests/{{ organization }}Test/Zed/{{ module }}/Business/"

preSpryks:
  - AddZedBusinessTestSuite
