spryk: template
description: "Adds a new *module*BusinessFactory to the Zed application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Business/ZedBusinessFactory.php.twig

  targetFilename:
    value: "{{ module }}BusinessFactory.php"

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
  - AddModule

postSpryks:
  - AddZedBusinessFacade
  - AddZedDependencyProvider
  - AddZedConfig
