spryk: schema
description: "Adds a new table to the spy_*targetModule*.schema.xml."
mode: "all"

arguments:
  module:
    inherit: true
  targetModule: ~
  tableName: ~

  organization:
    inherit: true
    default: Spryker

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Persistence/Propel/Schema/spy_{{ targetModule | underscored }}.schema.xml"

preSpryks:
  - AddZedPersistencePropelSchema


postSpryks:
  - AddZedPersistencePropelAbstractEntity
  - AddZedPersistencePropelAbstractQuery
