spryk: update-yml
description: "Adds the include for the Zed test suite to the codeception.yml."
mode: "core|sdk|eco"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  afterElement:
    value: actor

  addToElement:
    value: include

  content:
    value: "tests/{{ organization }}Test/Zed/{{ module }}"

  targetPath:
    value: "codeception.yml"

preSpryks:
  - AddModuleCodeceptionConfiguration
