spryk: template
description: "Adds a new *module*To*dependentModule*ClientInterface."
mode: "all"

arguments:
  module:
    inherit: true
    moduleFilter:
      application: Zed

  dependentModule:
    inherit: true
    moduleFilter:
      application: Client

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Dependency/Client/ZedDependencyClientInterface.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ClientInterface.php"

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Dependency/Client/"

preSpryks:
  - AddZedDependencyClientBridge
