spryk: template
description: "Adds a new twig file to the *module* Presentation layer."
mode: "all"

config:
  noRender: true

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - RemoveControllerSuffixCallback

  controllerMethod:
    callback:
      - RemoveActionSuffixCallback

  template:
    value: Zed/Presentation/ZedPresentationTwig.twig

  targetFilename:
    value: "{{ controllerMethod | removeActionSuffix | dasherize | lcfirst }}.twig"

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Presentation/{{ controller | classNameShort | removeControllerSuffix }}/"

preSpryks:
  - AddZedCommunicationControllerAction
