spryk: template
description: "Adds a new README.md to the Modules root."
mode: "core|sdk|eco"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: README.md.twig

  targetPath:
    value: ""

preSpryks:
  - AddModule
