spryk: template
description: "Adds a new .gitignore to the Modules root."
mode: "core|sdk|eco"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: gitignore.twig

  targetFilename:
    value: .gitignore

  targetPath:
    value: ""

preSpryks:
  - AddModule
