spryk: template
description: "Adds a new .coveralls.yml to the Modules root."
mode: "core|sdk|eco"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  repositoryToken: ~

  template:
    value: coveralls.yml.twig

  targetFilename:
      value: .coveralls.yml

  targetPath:
    value: ""

preSpryks:
  - AddModule
