spryk: copyModule
description: "Copies a *module*."
priority: 1
mode: "core|sdk|eco"

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  toModule:
    inherit: true

  toOrganization:
    inherit: true
    default: Spryker

  sourcePath: ~

  targetPath: ~
