spryk: navigation
description: "Adds a new navigation node entry tho the *module* navigation.xml."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - RemoveControllerSuffixCallback

  controllerMethod:
    callback:
      - RemoveActionSuffixCallback

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Communication/navigation.xml"

preSpryks:
  - AddZedNavigationSchema
