spryk: structure
description: "Adds a new *module* Communication test suite directory."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  targetPath:
    value: ""

  directories:
    value:
      - "tests/{{ organization }}Test/Zed/{{ module }}/Communication/"

postSpryks:
  - AddZedCommunicationTestSuiteConfiguration
