spryk: template
description: "Adds a new *module*Repository to the Zed application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceRepository.php.twig

  targetFilename:
    value: "{{ module }}Repository.php"

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - AddModule

postSpryks:
  - AddZedPersistenceFactory
  - AddZedPersistenceRepositoryInterface

