spryk: template
description: "Adds a new *module*RepositoryInterface to the Zed application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceRepositoryInterface.php.twig

  targetFilename:
    value: "{{ module }}RepositoryInterface.php"

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - AddZedPersistenceRepository
