spryk: template
description: "Adds a new *module*PersistenceFactory to the Zed application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceFactory.php.twig

  targetFilename:
    value: "{{ module }}PersistenceFactory.php"

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - AddModule

