spryk: template
description: "Adds a new *Module*ClientDependencyProvider to the Client application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Client/ClientDependencyProvider.php.twig

  targetFilename:
    value: "{{ module }}DependencyProvider.php"

  targetPath:
    value: "src/{{ organization }}/Client/{{ module }}/"

preSpryks:
  - AddModule
