spryk: template
description: "Adds a new *module*.transfer.xml to the Shared application."
mode: "all"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Shared/transfer.xml.twig

  targetFilename:
    value: "{{ module | underscored }}.transfer.xml"

  targetPath:
    value: "src/{{ organization }}/Shared/{{ module }}/Transfer/"

preSpryks:
  - AddModule
