spryk: template
description: "Adds a new *module*To*dependentModule*ServiceBridge."
mode: "core|sdk|eco"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  application:
    value: Yves

  dependentModule: ~

  dependentModuleOrganization:
    default: Spryker

  template:
    value: Yves/Dependency/Service/YvesDependencyServiceBridge.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ServiceBridge.php"

  targetPath:
    value: "src/{{ organization }}/Yves/{{ module }}/Dependency/Service/"

preSpryks:
  - AddModule

postSpryks:
  - AddYvesDependencyServiceInterface
  - AddYvesDependencyServiceFactoryMethod
  - AddYvesDependencyServiceDependencyProviderMethod
  - AddYvesDependencyServiceDependencyProviderConstant:
      arguments:
          name:
            value: "SERVICE_{{ dependentModule | underscored | upper }}"
          value:
            value:  "{{ dependentModule | camelCaseToWhitespace | lower }} service"
          visibility:
            value:  "public"
