spryk: template
description: "Adds a new *module*To*dependentModule*ServiceInterface."
mode: "all"

arguments:
  module:
    inherit: true
  dependentModule: ~

  organization:
    inherit: true
    default: Spryker

  template:
    value: Yves/Dependency/Service/YvesDependencyServiceInterface.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ServiceInterface.php"

  targetPath:
    value: "src/{{ organization }}/Yves/{{ module }}/Dependency/Service/"

preSpryks:
  - AddYvesDependencyServiceBridge
