spryk: template
description: "Adds a new *module*To*dependentModule*ClientBridge."
mode: "core|sdk|eco"

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  dependentModule: ~

  dependentModuleOrganization:
    default: Spryker


  template:
    value: Yves/Dependency/Client/YvesDependencyClientBridge.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ClientBridge.php"

  targetPath:
    value: "src/{{ organization }}/Yves/{{ module }}/Dependency/Client/"

preSpryks:
  - AddModule

postSpryks:
  - AddYvesDependencyClientInterface
  - AddYvesDependencyClientFactoryMethod
  - AddYvesDependencyClientDependencyProviderMethod
  - AddYvesDependencyClientDependencyProviderConstant:
      arguments:
          name:
            value: "CLIENT_{{ dependentModule | underscored | upper }}"
          value:
            value:  "{{ dependentModule | camelCaseToWhitespace | lower }} client"
          visibility:
            value:  "public"
