spryk: bridgeMethods
description: "Adds a new method to the *module* dependency Client bridge."
priority: 1
mode: "core|sdk|eco"

arguments:

  module:
    inherit: true
  organization:
    inherit: true
    default: Spryker

  dependentModule: ~

  methods:
    type: MethodNameChoice
    choiceLoader: ClientMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - module
      - choiceLoader

  template:
    value: Yves/Dependency/YvesDependencyBridgeMethod.php.twig

  dependencyType:
    value: Client

  sourceClass:
    value: "{{ organization }}\\Client\\{{ dependentModule }}\\{{ dependentModule }}Client"

  target:
    value: "{{ organization }}\\Yves\\{{ module }}\\Dependency\\Client\\{{ module }}To{{ dependentModule }}ClientBridge"

preSpryks:
  - AddYvesDependencyClientBridge

postSpryks:
  - AddYvesDependencyClientBridgeInterfaceMethod
